GET https://claseframework-e5od--3000--6ba59070.local-corp.webcontainer.io/tasks

###

POST https://claseframework-e5od--3000--6ba59070.local-corp.webcontainer.io/tasks
content-type: application/json

{
    "name": "alex"
}